### ISSUE TITLE
Miaou miaou

### ISSUE THREAD

**Issue by mitsuakki** [szerookii/szerookii#1]
Don't forget that you also love cats, you know, the thing that goes meow meow

**Comment by Seyz123** [comment]
Miaou miaou ... oe réel

**Comment by Mitsuaaki** [comment]
A moins qu'un chat fasse, waouf waouf, oui

**Comment by Seyz123** [comment]
oeeee mais ct pas ça la réf

**Comment by Seyz123** [comment]
genre meow meow [...] oeeee

**Comment by Mitsuaaki** [comment]
aaaaaaaaaaaaah putain je l'ai c'est bon, long a la détente ajd mdr 
https://www.youtube.com/watch?v=P8KwMnA0P6g&ab_channel=%D9%85%D9%8A%D9%85%D8%B2%D8%A7%D9%84%D8%B2%D9%86%D8%AC%D9%8A

**Comment by Seyz123** [comment]
ouais j'pense c'est celle-ci oe

**Comment by Mitsuaaki** [comment]
bref rajoute que tu aimes les chats où je débarque dans ta casa comme on dit dans mon cartel

**Comment by Seyz123** [comment]
tu t'es crus au mexique ou quoi

**Comment by Mitsuaaki** [comment]
[Voici une photo de moi, au Mexique justement](https://media.nouvelobs.com/referentiel/633x306/15676409.jpg)

**Comment by Seyz123** [comment]
[je pense c'est ça](https://open.spotify.com/album/3tkD2GnEbamX5WRdZ0Z2Lr)
